# Judgmental forecasts

[The source of the chapter](https://otexts.com/fpp3/judgmental.html)

The judgmental forecasting is used:

-   there are no available data, so that statistical methods are not applicable and judgmental forecasting is the only feasible approach;
-   data are available, statistical forecasts are generated, and these are then adjusted using judgment;
-   data are available and statistical and judgmental forecasts are generated independently and then combined.

## Beware of limitations

[The source of the section](https://otexts.com/fpp3/judgmental-limitations.html)

> Judgmental forecasts are **subjective**, and therefore do not come free of bias or limitations.

## Key principles

[The source of the section](https://otexts.com/fpp3/judgmental-principles.html)

-   Set the forecasting task clearly and concisely
-   Implement a systematic approach
-   Document and justify
-   Systematically evaluate forecasts
-   Segregate forecasters and users

## The Delphi method

[The source of the section](https://otexts.com/fpp3/delphimethod.html)

The Delphi method generally involves the following stages:

1.  A panel of experts is assembled.

2.  Forecasting tasks/challenges are set and distributed to the experts.

3.  Experts return initial forecasts and justifications. These are compiled and summarised in order to provide feedback.

4.  Feedback is provided to the experts, who now review their forecasts in light of the feedback. This step may be iterated until a satisfactory level of consensus is reached.

5.  Final forecasts are constructed by aggregating the experts' forecasts.

## Forecasting by analogy

[The source of the section](https://otexts.com/fpp3/analogies.html)

The structured approach involves the following steps.

1.  A panel of experts who are likely to have experience with analogous situations is assembled.

2.  Tasks/challenges are set and distributed to the experts.

3.  Experts identify and describe as many analogies as they can, and generate forecasts based on each analogy.

4.  Experts list similarities and differences of each analogy to the target situation, then rate the similarity of each analogy to the target situation on a scale.

5.  Forecasts are derived by the facilitator using a set rule. This can be a weighted average, where the weights can be guided by the ranking scores of each analogy by the experts.

## Scenario forecasting

[The source of the section](https://otexts.com/fpp3/scenarios.html)

> The scenarios are generated by considering all possible factors or drivers, their relative impacts, the interactions between them, and the targets to be forecast.

> **Important!** With scenario forecasting, decision makers often participate in the generation of scenarios. While this may lead to some biases.

## New product forecasting

[The source of the section](https://otexts.com/fpp3/new-products.html)

## Judgmental adjustments

[The source of the section](https://otexts.com/fpp3/judgmental-adjustments.html)
